import pickle
import time

def convert_cookies():
    print("Converting cookies.pkl to cookies.txt...")
    try:
        with open("cookies.pkl", "rb") as f:
            cookies = pickle.load(f)
            
        with open("cookies.txt", "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by python script\n\n")
            
            for cookie in cookies:
                # Netscape format:
                # domain  flag  path  secure  expiration  name  value
                
                domain = cookie.get('domain', '')
                # flag: TRUE if domain starts with .
                flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                path = cookie.get('path', '/')
                secure = 'TRUE' if cookie.get('secure') else 'FALSE'
                expiry = str(int(cookie.get('expiry', time.time() + 3600)))
                name = cookie.get('name', '')
                value = cookie.get('value', '')
                
                line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n"
                f.write(line)
                
        print(f"✅ Converted {len(cookies)} cookies to cookies.txt")
        
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    convert_cookies()
