import pandas as pd
import os

urls = [
    "https://www.instagram.com/reel/DJs-lGHy9hM/",
    "https://www.instagram.com/reel/DJrKOFWPGvc/?hl=en",
    "https://www.instagram.com/reel/DM4_qshB3le/?igsh=aDdkcWxndG40Z2Qx",
    "https://www.instagram.com/p/DMsYnNeJnSp/",
    "https://www.instagram.com/reel/DM5F3Vzq6TN/?igsh=MWZ2dzZxb2xmanM5ZA%3D%3D",
    "https://www.instagram.com/reel/DM5WV8-Sg2v/?igsh=dzZtaWEzYjZjZjN5",
    "https://www.instagram.com/reel/DM7mxJHJH0q/?igsh=NXF6MTM5NGtwdmw4",
    "https://www.instagram.com/reel/DM7uMlcoJwj/?igsh=enJ0cW5jNXI5cjAw",
    "https://www.instagram.com/reel/DMh8usYM8Gj/?igsh=MTFzM2NuOGR4bjJucw%3D%3D",
    "https://www.instagram.com/reel/DMmWgk-I1WK/?igsh=djM0dGYzMmQ4MW1u",
    "https://www.instagram.com/reel/DMu6KPKyzdy/?igsh=MTl2OGgxaXhhaGtqZA%3D%3D",
    "https://www.instagram.com/reel/DFXl767SXo2/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/p/DDrEn5DyP-6/",
    "https://www.instagram.com/p/DDwmfrrTc2i/",
    "https://www.instagram.com/reel/DD9YxAqvaUK/",
    "https://www.instagram.com/reel/DFNhbOXPio2/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/p/DDuH1EGvzIT/",
    "https://www.instagram.com/p/DD63HW1T0ci/",
    "https://www.instagram.com/p/DDmMTIxvf_-/",
    "https://www.instagram.com/p/DDkAvqyoZTl/",
    "https://www.instagram.com/reel/DMDZGz-J6nf/?utm_source=ig_web_copy_link&igsh=MW10cmh3YW05MTZ5Zg%3D%3D",
    "https://www.instagram.com/reel/DMFn-P_osto/?igsh=MWJlemw4OTVpMWoydg%3D%3D",
    "https://www.instagram.com/p/DMAWxS9hkHb/",
    "https://www.instagram.com/reel/DMP9HPYS7vJ/?igsh=MnU4c2ZtanNsaHFu",
    "https://www.instagram.com/reel/DMAXktXNvY3/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DMKtrOaJAMu/?utm_source=ig_web_copy_link",
    "https://www.instagram.com/reel/DMAcrgmzemP/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DMSrb55q0eb/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DMDQADGpmfI/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DMAqzCXpx1T/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DMcKfYpSd2Q/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DMAZWhYCVim/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DMaZ9EYNiIB/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/p/DMIOxVuSaNF",
    "https://www.instagram.com/reel/DNFvhHjoesl/",
    "https://www.instagram.com/reel/DNM94IhIo4I/?igsh=MWRpZHM0NHNkZDFqMA%3D%3D",
    "https://www.instagram.com/reel/DJ_OMBYKK2H/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DJ9EbAGsBq_/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DKPLJlYTGxQ/",
    "https://www.instagram.com/reel/DKb-ABMqh64/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DKPM_NkyBZY/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DKJ9Ef1zg15/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DKRxJelTCSJ/",
    "https://www.instagram.com/reel/DKYUoCgz0Tb/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DKMwPW7saMI/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DKjnPo1Pkwi/?igsh=MXVpbHl0MTd6cWVqaA%3D%3D",
    "https://www.instagram.com/reel/DKHc5X5z-M2/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DKcFd_IRkQf/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DKJkjzyyYrD/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DJ_v3LfzvN2/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DJ_MpDfPXKd/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DNiMgpXPDqA/",
    "https://www.instagram.com/reel/DOD2x1mCX0f/",
    "https://www.instagram.com/reel/DOGLgyfiRXj/",
    "https://www.instagram.com/reel/DOFktSiE8oz/",
    "https://www.instagram.com/p/DOOITgKj6Hw/",
    "https://www.instagram.com/p/DOIqBeDkcct/",
    "https://www.instagram.com/p/DPawHy8k0D4/",
    "https://www.instagram.com/p/DO-9GQxgcxn/",
    "https://www.instagram.com/reel/DOgCxfukpXX/",
    "https://www.instagram.com/p/DLmztSMyfec/",
    "https://www.instagram.com/p/DLsCUwfJatX/",
    "https://www.instagram.com/p/DLjipWKxgxj/",
    "https://www.instagram.com/reel/DIohD7gTcbd/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/reel/DIYrnS2zff7/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/p/DMKmHbBPt8a/",
    "https://www.instagram.com/p/DIY3YO5pLbL/",
    "https://www.instagram.com/reel/DI_a1BAPwFK/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    "https://www.instagram.com/p/DIY2-ksyxkp/",
    "https://www.instagram.com/p/DIbTLIVSCl7/",
    "https://www.instagram.com/p/DIaiqnzyvno/",
    "https://www.instagram.com/reel/DMexMRsiIFv/",
    "https://www.instagram.com/reel/DJrQEE6SqDV/",
    "https://www.instagram.com/reel/DJ_x1LzvaBg/",
    "https://www.instagram.com/p/DHgDPunyv7I",
    "https://www.instagram.com/p/DHiheBOyOKH",
    "https://www.instagram.com/p/DHcuBLhvMHh",
    "https://www.instagram.com/p/C-p0dbPq0UA/?hl=en",
    "https://www.instagram.com/reel/C-er787N7-I/?igsh=ejBxcGdhMGIwYTIz",
    # YOUTUBE URL REMOVED: "https://www.youtube.com/watch?v=TTab3l3ZUeQ",
    "https://www.instagram.com/reel/DKL-k9TSVTn/?igsh=MTNxZnVuZDBycHJoaQ%3D%3D",
    "https://www.instagram.com/reel/DKMr797zwUe/?igsh=MTBpN2JhcG4yYjQ3",
    "https://www.instagram.com/reel/DKL_XB0NBRD/?igsh=MTNkdTFmcnJhenZqcw%3D%3D",
    "https://www.instagram.com/reel/DKOhkJHtIWi/?igsh=MWlsaWk0MmpqeWhydQ%3D%3D",
    "https://www.instagram.com/reel/DKMI2kquwda/",
    "https://www.instagram.com/reel/DKOgyVrtxmx/",
    "https://www.instagram.com/reel/DKMo9davo8A/?igsh=MTFtb2h4MjVnYjZjdA%3D%3D",
    "https://www.instagram.com/reel/DKOqDEZz9NV/?igsh=dzM0eXBpdjI4NG05",
    "https://www.instagram.com/reel/DKMpM1SJnYm/?igsh=NjFoN3V3bTZtd255",
    "https://www.instagram.com/reel/DJMa8b9TPgY/?igsh=azluM3c3c2VxcHFo",
    "https://www.instagram.com/reel/DJD51I-hWR5/",
    "https://www.instagram.com/reel/DI8Qpnfx9eb/?igsh=dXlmbTlkem5oa2Fx",
    "https://www.instagram.com/reel/DJRStQyTqsn/",
    "https://www.instagram.com/reel/DJnzjlrs6wi/?igsh=bWZlanJ1cmVhY280",
    "https://www.instagram.com/reel/DJtdeNjPC4H/",
    "https://www.instagram.com/reel/DJ3BmSfOFRr/?igsh=NHZjcnZ0bXQyNG0x",
    "https://www.instagram.com/reel/DJoju-1zDzS/?igsh=MWNscTJmcGdqZTdxYQ%3D%3D"
]

# Ensure input directory exists
if not os.path.exists('input'):
    os.makedirs('input')

# Create DataFrame
df = pd.DataFrame(urls, columns=['INSTAGRAM URL'])

# Save to Excel
output_file = 'input/INSTAURL.xlsx'
df.to_excel(output_file, index=False)

print(f"✅ Successfully created {output_file} with {len(urls)} URLs")
